import { db, client } from '../src/db/client';
import { users, suppliers, invoices } from '../src/db/schema';
import { hashPassword } from '../src/utils/password';
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

// Generate a secure random password
function generatePassword(length: number = 16): string {
	const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnpqrstuvwxyz23456789!@#$%^&*';
	let password = '';
	const crypto = require('crypto');
	const array = new Uint8Array(length);
	crypto.getRandomValues(array);
	
	for (let i = 0; i < length; i++) {
		password += chars[array[i] % chars.length];
	}
	return password;
}

// Real supplier names from legacy database
const supplierNames = [
	'Cv Sukses Mandiri',
	'PT. Air Mandiri Distribusindo',
	'PT. Akasia Inter Nusa',
	'PT. Antarmitra Sembada',
	'PT. Anugerah Argon Mandiri',
	'PT. Anugerah Pharmindo Lestari',
	'PT. Bahtera Laju Nusantara',
	'PT. Bangun Citra Lestari',
	'PT. Berkat Sukses Sentosa',
	'PT. Cahaya Makmur Prima Sejahtera',
	'PT. Cahaya Pelita Borneo',
	'PT. Cahaya Putri Bintang',
	'PT. Daya Muda Agung',
	'PT. Dialogue Garmindo Utama',
	'PT. Enseval Putra Mega Trading',
	'PT. IndoMarco Adi Prima',
	'PT. Intiboga Mandiri',
	'PT. Kreasi Perdana Indonesia',
	'PT. Laris Sukses Abadi',
	'PT. Laut Indah Jaya',
	'PT. Laut Timur Ardiprima',
	'PT. Mahkota Lestari',
	'PT. Maju Anugerah Jaya Usaha',
	'PT. Maju Anugerah Jaya Utama',
	'PT. Marga Nusantara Jaya',
	'PT. Mensa Bina Sukses',
	'PT. Mitra Usaha Sukses Sejahtera',
	'PT. Mulia Anugerah Distribusindo',
	'PT. Obor Baru Maju',
	'PT. Oliver Bayi Andalan',
	'PT. Parit Padang Global',
	'PT. Penta Valent',
	'PT. Pulau Baru Jaya',
	'PT. Pundi Mas Sejahtera',
	'PT. Putera Raja Sejahtera',
	'PT. Sejahtera Sukses Sejati Banjarmasin',
	'PT. Selamat Sejahtera Sejati',
	'PT. Semangat Selamat Sejahtera',
	'PT. Sinar Alam Timur',
	'PT. Sumber Sehat Makmur',
	'PT. Surya Timur Raya',
	'PT. Tempo',
	'PT. Tigaraksa Satria',
	'PT. Wildan Cahaya Asri',
	'Winning Mulia',
];

async function seed() {
	console.log('🌱 Seeding database...');

	try {
		// Create admin user with auto-generated password (skip if already exists)
		try {
			console.log('Creating admin user...');
			
			// Generate secure random password
			const plainPassword = generatePassword(16);
			const hashedPassword = await hashPassword(plainPassword);
			
			// Create admin user
			await db.insert(users).values({
				username: 'admin',
				password: hashedPassword,
				role: 'admin',
			});
			
			// Save credentials to file
			const credentialsPath = join(process.cwd(), 'ADMIN_CREDENTIALS.txt');
			const credentialsContent = `
===========================================
ADMIN CREDENTIALS - GENERATED BY SEED
===========================================

Username: admin
Password: ${plainPassword}

⚠️  IMPORTANT SECURITY NOTES:
1. This password was auto-generated during seeding
2. Save this password in a secure location
3. Change this password after first login
4. Delete this file after saving the password
5. Never commit this file to version control

Generated: ${new Date().toISOString()}
===========================================
`;
			
			writeFileSync(credentialsPath, credentialsContent);
			
			console.log('✅ Admin user created!');
			console.log('📄 Credentials saved to: ADMIN_CREDENTIALS.txt');
			console.log('⚠️  IMPORTANT: Save the password from ADMIN_CREDENTIALS.txt and delete the file!');
		} catch (error: any) {
			if (error.code === '23505') {
				console.log('Admin user already exists, skipping...');
			} else {
				throw error;
			}
		}

		// Insert suppliers (skip if already exists)
		console.log(`Inserting ${supplierNames.length} suppliers...`);
		let insertedCount = 0;
		let skippedCount = 0;
		for (const name of supplierNames) {
			try {
				await db.insert(suppliers).values({ name });
				insertedCount++;
			} catch (error: any) {
				if (error.code === '23505') {
					// Supplier already exists, skip
					skippedCount++;
				} else {
					throw error;
				}
			}
		}
		console.log(`✅ Inserted ${insertedCount} suppliers, skipped ${skippedCount} duplicates`);

		// Import legacy invoices
		console.log('\n📦 Importing legacy invoices...');
		try {
			const legacyDbPath = join(process.cwd(), '..', 'legacy', 'backend', 'db.json');
			const legacyData = JSON.parse(readFileSync(legacyDbPath, 'utf-8'));
			
			if (legacyData.invoices && Array.isArray(legacyData.invoices)) {
				const legacyInvoices = legacyData.invoices;
				console.log(`Found ${legacyInvoices.length} invoices in legacy database`);
				
				let importedCount = 0;
				let errorCount = 0;
				
				for (const invoice of legacyInvoices) {
					try {
						await db.insert(invoices).values({
							supplier: invoice.supplier || 'Unknown',
							branch: invoice.branch || 'Kuripan',
							date: invoice.date || new Date().toISOString().split('T')[0],
							invoiceNumber: invoice.invoiceNumber || `LEGACY-${Date.now()}`,
							total: invoice.total || '0',
							description: invoice.description || null,
							paid: invoice.paid || false,
							paidDate: invoice.paidDate || null,
							timestamp: invoice.timestamp ? new Date(invoice.timestamp) : new Date(),
						});
						importedCount++;
						
						// Show progress every 100 invoices
						if (importedCount % 100 === 0) {
							console.log(`   Imported ${importedCount}/${legacyInvoices.length} invoices...`);
						}
					} catch (error: any) {
						errorCount++;
						// Skip duplicate or invalid entries
						if (errorCount <= 5) {
							console.warn(`   Warning: Failed to import invoice ${invoice.invoiceNumber}: ${error.message}`);
						}
					}
				}
				
				console.log(`✅ Imported ${importedCount} legacy invoices`);
				if (errorCount > 0) {
					console.log(`⚠️  Skipped ${errorCount} invoices due to errors`);
				}
			} else {
				console.log('No invoices found in legacy database');
			}
		} catch (error: any) {
			console.log(`⚠️  Could not import legacy invoices: ${error.message}`);
			console.log('Continuing without legacy data...');
		}

		console.log('\n✅ Seeding completed successfully!');
		console.log('📄 Check ADMIN_CREDENTIALS.txt for admin login details');
	} catch (error) {
		console.error('❌ Seeding failed:', error);
		process.exit(1);
	} finally {
		await client.end();
	}
}

seed();
